from pathlib import Path

PATH_ROOT: Path = Path(__file__).parent.parent
PATH_DATA: Path = PATH_ROOT / "data"
PATH_DATA_EXTERNAL: Path = PATH_DATA / "external"
PATH_DATA_GENERATED: Path = PATH_DATA / "generated"
PATH_DATA_ANNOTATED: Path = PATH_DATA / "annotated"

PATH_PLOTS = PATH_DATA_GENERATED / "plots"

PATH_DATA_RESULTS: Path = PATH_DATA / "generated" / "results"

PATH_DATA_ANNOTATED_QUALITY = PATH_DATA_ANNOTATED / "quality"
PATH_DATA_ANNOTATED_QUALITY_XMI: Path = PATH_DATA_ANNOTATED / "xmi"
PATH_DATA_ANNOTATED_QUALITY_JSONCAS: Path = PATH_DATA_ANNOTATED / "jsoncas"

PATH_DATA_ANNOTATED_COVERAGE = PATH_DATA_ANNOTATED / "coverage"
PATH_DATA_ANNOTATED_COVERAGE_XMI: Path = PATH_DATA_ANNOTATED_COVERAGE / "xmi"
PATH_DATA_ANNOTATED_COVERAGE_JSONCAS: Path = PATH_DATA_ANNOTATED_COVERAGE / "jsoncas"

PATH_DATA_PDFS: Path = PATH_DATA_EXTERNAL / "pdfs"
PATH_DATA_PDFS_SELECTED: Path = PATH_DATA_EXTERNAL / "pdfs_selected"
PATH_DATA_PDFS_CHUNKED: Path = PATH_DATA_EXTERNAL / "pdfs_chunked"

PATH_DATA_PDFS_SELECTED_COVERAGE = PATH_DATA_EXTERNAL / "pdfs_coverage"

PATH_DATA_ACL_ANTHOLOGY: Path = PATH_DATA_EXTERNAL / "acl-anthology"
PATH_DATA_ACL_ANTHOLOGY_DATA: Path = PATH_DATA_ACL_ANTHOLOGY / "data"

PATH_DATA_ACL_ANTHOLOGY_XML: Path = PATH_DATA_ACL_ANTHOLOGY_DATA / "xml"
PATH_DATA_ACL_ANTHOLOGY_YAML: Path = PATH_DATA_ACL_ANTHOLOGY_DATA / "yaml"

PATH_DATA_PAPERS_WITH_CODE: Path = PATH_DATA_EXTERNAL / "paperswithcode"
PATH_DATA_PAPERS_WITH_CODE_DATASETS_GZ: Path = PATH_DATA_PAPERS_WITH_CODE / "datasets.json.gz"
PATH_DATA_PAPERS_WITH_CODE_DATASETS_JSON: Path = PATH_DATA_PAPERS_WITH_CODE / "datasets.json"
PATH_DATA_PAPERS_WITH_CODE_PAPERS_GZ: Path = PATH_DATA_PAPERS_WITH_CODE / "papers-with-abstracts.json.gz"
PATH_DATA_PAPERS_WITH_CODE_PAPERS_JSON: Path = PATH_DATA_PAPERS_WITH_CODE / "papers.json"
PATH_DATA_PAPERS_WITH_CODE_LINKS_GZ: Path = PATH_DATA_PAPERS_WITH_CODE / "links-between-papers-and-code.json.gz"
PATH_DATA_PAPERS_WITH_CODE_LINKS_JSON: Path = PATH_DATA_PAPERS_WITH_CODE / "links.json"
PATH_DATA_PAPERS_WITH_CODE_EVALUATION_TABLES_JSON: Path = PATH_DATA_PAPERS_WITH_CODE / "evaluation_tables.json"


PATH_DATA_SELECTED_PAPERS_XLSX: Path = PATH_DATA_GENERATED / "pwc_selected_papers.xlsx"
PATH_DATA_SELECTED_PAPERS_CSV: Path = PATH_DATA_GENERATED / "pwc_selected_papers.csv"
